# -*- coding: utf-8 -*-
"""Prediksi_Harga_Smartphone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CLzVAWfS0VdiXLPyxEuaiiOjEf0i_pXG
"""

# Import Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from google.colab import files

uploaded = files.upload()

data = pd.read_csv("train.csv")

data.head()

data.describe()

print(data.columns)

data.isnull().sum()

data.columns

X = data.drop("price_range", axis=1)
y = data["price_range"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

akurasi = accuracy_score(y_test, y_pred)

print("Akurasi Model:", akurasi)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.xlabel("Prediksi")
plt.ylabel("Data Asli")
plt.title("Confusion Matrix")

plt.savefig("output/confusion_matrix.png", dpi=300, bbox_inches="tight")

plt.show()

plt.figure(figsize=(20,10))

plot_tree(
    model,
    filled=True,
    feature_names=X.columns,
    class_names=["0","1","2","3"],
    fontsize=8
)

plt.savefig("output/decision_tree.png", dpi=300, bbox_inches="tight")

plt.show()

data_baru = [[842,0,2.2,0,1,0,7,0.6,188,2,2,1,20,756,2549,9,7,19,0,0]]

hasil = model.predict(data_baru)

print("Prediksi Kelas Harga Smartphone:", hasil[0])

import os

os.makedirs("output", exist_ok=True)

plt.savefig("output/confusion_matrix.png", dpi=300, bbox_inches="tight")

